CREATE SEQUENCE IF NOT EXISTS fornecedor_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS fornecedor (
    id BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('fornecedor_id_seq'),
    nome VARCHAR(255) NOT NULL,
    cnpj VARCHAR(18) UNIQUE NOT NULL,
    email VARCHAR(150) NOT NULL,
    telefone VARCHAR(14) NOT NULL,
    ativo BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_tmsp TIMESTAMP WITHOUT TIME ZONE
);